package models

import (
	"time"
)

// F3 struct ánh xạ bảng F3
type Orders struct {
	MaDonHang                string    `json:"maDonHang" gorm:"primaryKey;type:VARCHAR(100)"`
	MaTracking               string    `json:"maTracking" gorm:"type:VARCHAR(100)"`
	NgayLenDon               time.Time `json:"ngayLenDon" gorm:"type:DATETIME"`
	Name                     string    `json:"name" gorm:"type:VARCHAR(255)"`
	Phone                    string    `json:"phone" gorm:"type:VARCHAR(50)"`
	Add                      string    `json:"add" gorm:"type:VARCHAR(255)"`
	City                     string    `json:"city" gorm:"type:VARCHAR(100)"`
	State                    string    `json:"state" gorm:"type:VARCHAR(100)"`
	Zipcode                  string    `json:"zipcode" gorm:"type:VARCHAR(50)"`
	MatHang                  string    `json:"matHang" gorm:"type:VARCHAR(255)"`
	TenMatHang1              string    `json:"tenMatHang1" gorm:"type:VARCHAR(255)"`
	SoLuongMatHang1          int       `json:"soLuongMatHang1" gorm:"type:INT"`
	TenMatHang2              string    `json:"tenMatHang2" gorm:"type:VARCHAR(255)"`
	SoLuongMatHang2          int       `json:"soLuongMatHang2" gorm:"type:INT"`
	QuaTang                  string    `json:"quaTang" gorm:"type:VARCHAR(255)"`
	SoLuongQuaKem            int       `json:"soLuongQuaKem" gorm:"type:INT"`
	GiaBan                   float64   `json:"giaBan" gorm:"type:DECIMAL(15,2)"`
	LoaiTienThanhToan        string    `json:"loaiTienThanhToan" gorm:"type:VARCHAR(50)"`
	TongTienVND              float64   `json:"tongTienVND" gorm:"type:DECIMAL(15,2)"`
	HinhThucThanhToan        string    `json:"hinhThucThanhToan" gorm:"type:VARCHAR(100)"`
	GhiChu                   string    `json:"ghiChu" gorm:"type:TEXT"`
	NhanVienSale             string    `json:"nhanVienSale" gorm:"type:VARCHAR(100)"`
	NhanVienMarketing        string    `json:"nhanVienMarketing" gorm:"type:VARCHAR(100)"`
	NvVanDon                 string    `json:"nvVanDon" gorm:"type:VARCHAR(100)"`
	KetQuaCheck              string    `json:"ketQuaCheck" gorm:"type:VARCHAR(100)"`
	TrangThaiGiaoHangNB      string    `json:"trangThaiGiaoHangNB" gorm:"type:VARCHAR(100)"`
	LyDo                     string    `json:"lyDo" gorm:"type:VARCHAR(255)"`
	DonViVanChuyen           string    `json:"donViVanChuyen" gorm:"type:VARCHAR(100)"`
	TrangThaiThuTien         string    `json:"trangThaiThuTien" gorm:"type:VARCHAR(100)"`
	NgayHenDayDon            time.Time `json:"ngayHenDayDon" gorm:"type:DATETIME"`
	SoTienThucThu            float64   `json:"soTienThucThu" gorm:"type:DECIMAL(15,2)"`
	NgayUpBill               time.Time `json:"ngayUpBill" gorm:"type:DATETIME"`
	AnhBill                  string    `json:"anhBill" gorm:"type:VARCHAR(255)"`
	NgayChuyenKhoan          time.Time `json:"ngayChuyenKhoan" gorm:"type:DATETIME"`
	LoaiThanhToan            string    `json:"loaiThanhToan" gorm:"type:VARCHAR(100)"`
	TenNguoiChuyenKhoan      string    `json:"tenNguoiChuyenKhoan" gorm:"type:VARCHAR(255)"`
	TaiKhoanNhan             string    `json:"taiKhoanNhan" gorm:"type:VARCHAR(255)"`
	SoTienDaNhan             float64   `json:"soTienDaNhan" gorm:"type:DECIMAL(15,2)"`
	TyGiaCuoc                float64   `json:"tyGiaCuoc" gorm:"type:DECIMAL(10,2)"`
	DonViTienDoiSoat         string    `json:"donViTienDoiSoat" gorm:"type:VARCHAR(50)"`
	NgayDoiSoatCuoc          time.Time `json:"ngayDoiSoatCuoc" gorm:"type:DATETIME"`
	TienShip                 float64   `json:"tienShip" gorm:"type:DECIMAL(15,2)"`
	TyGia                    float64   `json:"tyGia" gorm:"type:DECIMAL(10,2)"`
	DonViTienTeTinhCuoc      string    `json:"donViTienTeTinhCuoc" gorm:"type:VARCHAR(50)"`
	ThoiGianLenDon           time.Time `json:"thoiGianLenDon" gorm:"type:DATETIME"`
	GhiChuFFM                string    `json:"ghiChuFFM" gorm:"type:TEXT"`
	FfmThanhToan             string    `json:"ffmThanhToan" gorm:"type:VARCHAR(100)"`
	NgayDoiSoatBill          time.Time `json:"ngayDoiSoatBill" gorm:"type:DATETIME"`
	NgayKeToanDoiSoatFFM1    time.Time `json:"ngayKeToanDoiSoatFFM1" gorm:"type:DATETIME"`
	SoTienVeTKCtyFFM1        float64   `json:"soTienVeTKCtyFFM1" gorm:"type:DECIMAL(15,2)"`
	NgayKeToanDoiSoatFFM2    time.Time `json:"ngayKeToanDoiSoatFFM2" gorm:"type:DATETIME"`
	TienVietDaDoiSoat        float64   `json:"tienVietDaDoiSoat" gorm:"type:DECIMAL(15,2)"`
	NgayKeToanDoiSoatFFM3    time.Time `json:"ngayKeToanDoiSoatFFM3" gorm:"type:DATETIME"`
	Ca                       string    `json:"ca" gorm:"type:VARCHAR(50)"`
	TongSoTienFFM            float64   `json:"tongSoTienFFM" gorm:"type:DECIMAL(15,2)"`
	SoTienVeTKCtyNgoaiFFM    float64   `json:"soTienVeTKCtyNgoaiFFM" gorm:"type:DECIMAL(15,2)"`
	SoTienDonHangVeTKCty     float64   `json:"soTienDonHangVeTKCty" gorm:"type:DECIMAL(15,2)"`
	KeToanXacNhanThuTien     string    `json:"keToanXacNhanThuTien" gorm:"type:VARCHAR(50)"`
	ThongTinDon              string    `json:"thongTinDon" gorm:"type:TEXT"`
	ThongTinKhachHang        string    `json:"thongTinKhachHang" gorm:"type:TEXT"`
	ThongTinNhanSu           string    `json:"thongTinNhanSu" gorm:"type:TEXT"`
	PhanHoiTichCuc           string    `json:"phanHoiTichCuc" gorm:"type:TEXT"`
	PhanHoiTieuCuc           string    `json:"phanHoiTieuCuc" gorm:"type:TEXT"`
	Count                    int       `json:"count" gorm:"type:INT"`
	PhanLoaiKH               string    `json:"phanLoaiKH" gorm:"type:VARCHAR(100)"`
	XacNhanDon               string    `json:"xacNhanDon" gorm:"type:TEXT"`
	DienGiai                 string    `json:"dienGiai" gorm:"type:TEXT"`
	TenPage                  string    `json:"tenPage" gorm:"type:VARCHAR(255)"`
	GiaGoc                   float64   `json:"giaGoc" gorm:"type:DECIMAL(15,2)"`
	MauBacklist              string    `json:"mauBacklist" gorm:"type:VARCHAR(50)"`
	TrangThaiDon             string    `json:"trangThaiDon" gorm:"type:VARCHAR(100)"`
	TienChietKhau            float64   `json:"tienChietKhau" gorm:"type:DECIMAL(15,2)"`
	PhiShip                  float64   `json:"phiShip" gorm:"type:DECIMAL(15,2)"`
	TienSauShip              float64   `json:"tienSauShip" gorm:"type:DECIMAL(15,2)"`
	TenLenDon                string    `json:"tenLenDon" gorm:"type:VARCHAR(100)"`
	TaoBanIn                 string    `json:"taoBanIn" gorm:"type:VARCHAR(50)"`
	InDon                    string    `json:"inDon" gorm:"type:VARCHAR(50)"`
	CanhBaoBlacklistTrungDon string    `json:"canhBaoBlacklistTrungDon" gorm:"type:VARCHAR(100)"`
	KhuVuc                   string    `json:"khuVuc" gorm:"type:VARCHAR(100)"`
	PhiLuuKho                float64   `json:"phiLuuKho" gorm:"type:DECIMAL(15,2)"`
	Team                     string    `json:"team" gorm:"type:VARCHAR(100)"`
	MaCheck                  string    `json:"maCheck" gorm:"type:VARCHAR(100)"`
	GhiChuBEE                string    `json:"ghiChuBEE" gorm:"type:TEXT"`
	DanhDau                  string    `json:"danhDau" gorm:"type:VARCHAR(50)"`
	NgayDongHang             time.Time `json:"ngayDongHang" gorm:"type:DATETIME"`
	TrangThaiGiaoHang        string    `json:"trangThaiGiaoHang" gorm:"type:VARCHAR(100)"`
	ThoiGianGiaoDuKien       time.Time `json:"thoiGianGiaoDuKien" gorm:"type:DATETIME"`
	PhiShipNoiDiaMyUSD       float64   `json:"phiShipNoiDiaMyUSD" gorm:"type:DECIMAL(15,2)"`
	PhiXuLyDongHangUSD       float64   `json:"phiXuLyDongHangUSD" gorm:"type:DECIMAL(15,2)"`
	GhiChuKhac               string    `json:"ghiChuKhac" gorm:"type:TEXT"`
	NgayDoiSoat              time.Time `json:"ngayDoiSoat" gorm:"type:DATETIME"`
	TimeKeToanXacNhan        string    `json:"timeKeToanXacNhan" gorm:"type:TIME"`
	GhiChuVD                 string    `json:"ghiChuVD" gorm:"type:TEXT"`
	DonViThanhToan           string    `json:"donViThanhToan" gorm:"type:VARCHAR(100)"`
	TaiKhoanThanhToan        string    `json:"taiKhoanThanhToan" gorm:"type:VARCHAR(100)"`
	UpdateAt                 time.Time `json:"updateAt" gorm:"type:TIMESTAMP"`
	TrangThaiDVVC            string    `json:"trangThaiDVVC" gorm:"type:VARCHAR(100)"`
	NhapKho                  string    `json:"nhapKho" gorm:"type:VARCHAR(50)"`
	TongPhiVC                float64   `json:"tongPhiVC" gorm:"type:DECIMAL(15,2)"`
	TienCuoc                 float64   `json:"tienCuoc" gorm:"type:DECIMAL(15,2)"`
	SoTienDoiSoat            float64   `json:"soTienDoiSoat" gorm:"type:DECIMAL(15,2)"`
	MaDonHang2               string    `json:"maDonHang2" gorm:"type:VARCHAR(100)"`
	SstDonMKT                string    `json:"sstDonMKT" gorm:"type:VARCHAR(100)"`
	Cskh                     string    `json:"cskh" gorm:"type:VARCHAR(100)"`
	ThoiGianCutoff           time.Time `json:"thoiGianCutoff" gorm:"type:DATETIME"`
}
